---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::dn]
      - recipe[hadoop::rm]
      - recipe[hadoop::nm]
      - recipe[hadoop::jhs]
      - recipe[hadoop::ps]
      - recipe[flume::install]
#      - recipe[flume::ngs]
      - recipe[flume::localhost]
      - recipe[flume::test-ngs]
#      - recipe[flume::test-ngs-localhost]
    attributes:
         flume:
            ngs:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            hdfs:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            project: "lifegene"
            dataset: "samples"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            ps:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            native_libraries: "false"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
